---
title: "Injuries and Casualties in Taffic/Road Accidents (Kirikkale-Turkey)"
author: "Tamer Köksal"
date: "April 13, 2015"
output: 
    html_document:
        keep_md: True
---


```{r setoptions, echo=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r}
setwd("/Users/tamer/Documents/job/dataIncubator")
library(xlsx)
accidents <- read.xlsx("accidents.xlsx", 1)
```

***


```{r, fig.height=3}
############    PLOTS ################

require(ggplot2)
library(grid)
library(gridExtra)

# Casualties

p5 <- ggplot(accidents, aes(x = year, y = casualties))
p5 <- p5 + geom_line(color = "red") + geom_point() + xlab("Year") + ylab("Casualties") + ylim(0, max(accidents$casualties)) +
    geom_text(aes(y=casualties, label=format(casualties), hjust = 0.45, vjust = 1.7), size = 4) + scale_x_continuous(breaks=2007:2014)

# Injuries

p6 <- ggplot(accidents, aes(x = year, y = injuries))
p6 <- p6 + geom_line(color = "green") + geom_point() + xlab("Year") + ylab("Injuries") + ylim(min(accidents$injuries)-20, max(accidents$injuries)) +
    geom_text(aes(y=injuries, label=format(injuries), hjust = 0.45, vjust = 1.7), size = 4) + scale_x_continuous(breaks=2007:2014)

# Casualties and Injuries by Year

grid.arrange(p5, p6, ncol = 2, main = "Casualties and Injuries as a Result of Traffic Accidents\n")
```


***

